# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Corrigido para a versão v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2  # Alterado para v2 (a versão mais estável no momento)
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo
    - name: Run the application
      run: |
        python app.py  # Este passo está chamando o seu aplicativo
    - name: Test with pytest
      run: |
        pytest  # Certifique-se de que os testes estão configurados
