name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo

    - name: Run app.py com coleção 'players'
      run: |
        python app.py --colecao players

    - name: Run app.py com coleção 'cards'
      run: |
        python app.py --colecao cards

    - name: Run app.py com coleção 'battles'
      run: |
        python app.py --colecao battles
