name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo
    - name: Set OPCAO environment variable
      run: echo "OPCAO=1" >> $GITHUB_ENV  # Definindo um valor para a variável OPCAO
    - name: Run the application
      run: |
        python app.py  # Isso agora usará a variável OPCAO definida anteriormente
